# This is a basic workflow that is manually triggered

name: Copy Document Files

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  copy-docs:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     
      - name: Push generated webpage to another repository
        uses: nkoppel/push-files-to-another-repository@1.1.0
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-files: 'doc/'
          destination-username: 'pstaabp'
          destination-repository: 'pg-docs'
          destination-directory: 'doc-src'
          commit-email: 'peter.staab@gmail.com'
